name = "DatadogProfileUploader"
uuid = "4272d662-eee3-467e-bb71-20a4ae102b29"
authors = ["Pete Vilter <pete.vilter@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
